# Generated by Django 5.0.1 on 2024-01-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ_Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WillingToDonate', models.CharField(max_length=10, null=True)),
                ('PreviousOrganDonate', models.CharField(max_length=10, null=True)),
                ('LastOrganDonationDate', models.DateTimeField(max_length=50, null=True)),
                ('CheckupDate', models.DateTimeField(max_length=50, null=True)),
                ('Organ', models.CharField(max_length=50, null=True)),
                ('healthissuee', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField(max_length=50, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('donateblood', models.CharField(max_length=50, null=True)),
                ('dateofdonation', models.CharField(max_length=10, null=True)),
                ('healthissue', models.CharField(max_length=50, null=True)),
                ('bloodgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganApp.bloodgroup')),
            ],
        ),
    ]
