# Generated by Django 5.0.1 on 2024-01-22 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0002_organ_donation_blood_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('medicalConditions', models.CharField(max_length=50, null=True)),
                ('organPreferences', models.CharField(max_length=50, null=True)),
                ('bloodgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganApp.bloodgroup')),
            ],
        ),
    ]
