# Generated by Django 5.0.1 on 2024-01-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0005_alter_blood_donation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ_donation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganApp.registration'),
        ),
    ]
