# Generated by Django 5.0.1 on 2024-01-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0006_alter_organ_donation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_donation',
            old_name='user',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='organ_donation',
            old_name='user',
            new_name='public',
        ),
    ]
