# Generated by Django 5.0.1 on 2024-01-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0007_rename_user_blood_donation_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_donation',
            name='age',
        ),
        migrations.RemoveField(
            model_name='blood_donation',
            name='dob',
        ),
    ]
