# Generated by Django 5.0.1 on 2024-01-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0008_remove_blood_donation_age_remove_blood_donation_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_donation',
            name='bloodgroup',
        ),
    ]
