# Generated by Django 5.0.1 on 2024-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0009_remove_blood_donation_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ_donation',
            name='CheckupDate',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
