# Generated by Django 5.0.1 on 2024-01-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0010_alter_organ_donation_checkupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organ_donation',
            old_name='healthissuee',
            new_name='healthissue',
        ),
    ]
