# Generated by Django 5.0.1 on 2024-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0013_bloodbank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='availability',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
