# Generated by Django 5.0.1 on 2024-01-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0014_bloodbank_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='bloodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganApp.bloodgroup'),
        ),
    ]
