# Generated by Django 5.0.1 on 2024-01-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0015_bloodbank_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='bloodgroup',
        ),
        migrations.CreateModel(
            name='BloodStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=50, null=True)),
                ('bloodgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganApp.bloodgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganApp.bloodbank')),
            ],
        ),
    ]
