# Generated by Django 5.0.1 on 2024-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0016_remove_bloodbank_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstocks',
            name='bloodgroup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pledge_form',
            name='bloodgroup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='bloodgroup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blood_donation',
            name='bloodgroup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
    ]
