# Generated by Django 5.0.1 on 2024-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0017_alter_bloodstocks_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ_donation',
            name='LastOrganDonationDate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
