# Generated by Django 4.2.4 on 2024-03-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0021_remove_blood_donation_donateblood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organ_donation',
            old_name='hospitalaname',
            new_name='hospitalname',
        ),
    ]
