# Generated by Django 4.2.4 on 2024-04-09 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OrganApp', '0022_rename_hospitalaname_organ_donation_hospitalname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organ_donation',
            name='WillingToDonate',
        ),
        migrations.AddField(
            model_name='bloodstocks',
            name='bb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
