# Generated by Django 4.2.4 on 2024-04-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganApp', '0023_remove_organ_donation_willingtodonate_bloodstocks_bb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstocks',
            name='bb',
        ),
        migrations.AddField(
            model_name='organ_donation',
            name='checkupstatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
